core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('lista', views.ListaPresenca, name="lista")
    
]

lista_presenca/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

from core.enums import CURSOS, PROFESSORES, SEMESTRES

class Presenca(models.Model):
    NomeAluno = models.CharField(verbose_name="Nome_do_Aluno", max_length=100)
    NomeProfessor = models.IntegerField(verbose_name='Nome_do_Professor', choices=PROFESSORES)
    Semestre = models.IntegerField(verbose_name="Semestre", choices=SEMESTRES)
    NomeCurso = models.IntegerField(verbose_name='Nome_do_Curso', choices=CURSOS)
    

core/forms.py
from django import forms
from .models import Presenca

class PresencaForm(forms.ModelForm):
    class Meta: 
        model = Presenca
        fields = '__all__'

    def clean_NomeAluno(self):
        NomeAluno = self.cleaned_data['NomeAluno']
        return NomeAluno
    
    def clean_NomeProfessor(self):
        NomeProfessor = self.cleaned_data['NomeProfessor']
        return NomeProfessor

    def clean_Semestre(self): 
        Semestre = self.cleaned_data['Semestre']
        return Semestre
    
    def clean_NomeCurso(self):   
        NomeCurso = self.cleaned_data['NomeCurso']
        return NomeCurso
    
    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

core/views.py
from django.shortcuts import redirect, render

from core.enums import CURSOS, PROFESSORES, SEMESTRES
from .forms import PresencaForm
from .models import Presenca

def index(request):
    form = PresencaForm(request.POST)
    contexto = {
        'form': form
    }

    if request.method == 'POST':
        if form.is_valid():
            form_save = Presenca(**form.cleaned_data)
            form_save.save()
            return redirect('/')
        else:
            return render(request, "index.html")
    else:             
        return render (request, "index.html", contexto)

def ListaPresenca(request):
    if request.method == "GET":
        dados = Presenca.objects.all()
        lista_presenca = list()
        for item in  dados:
            presenca = {
                'nome_aluno' : item.NomeAluno,
                'nome_professor' : PROFESSORES [item.NomeProfessor -1][1],
                'semestre' : SEMESTRES [item.Semestre -1][1],
                'curso': CURSOS [item.NomeCurso -1][1]
            }
            lista_presenca.append(presenca)
        dados = lista_presenca
        return render (request, 'list.html', {'dados': dados})

core/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Cadastro Presença</title>
</head>


<body>
    <div class="container text-center">
        <div class="row align-items-start">
            <div>
                <form action={% url 'core:index' %} method="post">
                    {% csrf_token %}
                    <h1>Registro Presença</h1>
                    <div class="mb-3">
                        <label class="form-label" for="NomeAluno">Nome Completo:</label>
                        {{ form.NomeAluno }}
                    </div>
                    <div class="mb-3">
                        <label for="NomeProfessor">Nome do Professor:</label>
                        {{ form.NomeProfessor }}
                    </div>
                    <div class="mb-3">
                        <label for="Curso">Curso:</label>
                        {{ form.NomeCurso }}
                    </div>
                    <div class="mb-3">
                        <label for="Semestre">Semestre:</label>
                        {{ form.Semestre }}
                    </div>
            
                    <button class="btn btn-success" type="submit" value="Cadastro" >Enviar</button>
                </form>
                <a href="lista"><button class="btn btn-info">Listagem</button></a>
            </div>
        </div>
    </div>
    

</body>
</html>

core/templates/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Lista de Presenca</title>
</head>
<body>
    <div class="container text-center" >
        <div class="row align-items-start">
            <h1>Listagem de presença</h1>
        {% if not dados %}
        <h2>Sem presenças cadastradas</h2>
        {% else %}
        <h2>Presenças Cadastradas:</h2>
        <table>
            <thead>
                <tr>
                    <th>Nome do Aluno</th>
                    <th>Nome do Professor</th>
                    <th>Curso</th>
                    <th>Semestre</th>
                </tr>
            </thead>
            {% endif %}
            <tbody id="Presenca">
                {% for dado in dados %}
                <tr>
                    <td>{{ dado.nome_aluno }}</td>
                    <td>{{ dado.nome_professor }}</td>
                    <td>{{ dado.curso }}</td>
                    <td>{{ dado.semestre }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="/"><button>Cadastro</button></a>
        </div>
    </div>

</body>
</html>